version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/v2-payload"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/v2-dashboard"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/v2-registration"
    schedule:
      interval: "weekly" 