services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload
    ports:
      - "5433:5432"
    networks:
      - app-network

  payload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PAYLOAD_DATABASE_URI=postgres://payload:payload@postgres:5432/payload
      - PAYLOAD_SECRET=${PAYLOAD_SECRET} # Set this in your environment
    depends_on:
      - postgres
    volumes:
      - ./veent-payload/src:/app/src
      - payload-data:/app/data # named volume for persistent data
      - ./veent-payload/package.json:/app/package.json
      - ./veent-payload/package-lock.json:/app/package-lock.json
      - ./veent-payload/pnpm-lock.yaml:/app/pnpm-lock.yaml
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  payload-data:
